@host=http://localhost:3000

# @name WolfKillerHomePage
GET {{host}} HTTP/1.1

###
# @name WolfKillerUserInfo

GET http://localhost:5173 HTTP/1.1





###
GET  {{host}}/account/profile HTTP/1.1
###
# @name WolfKillerUserLogin
POST {{host}}/account/login HTTP/1.1
Content-Type: application/json;charset=utf-8

{
    "user_name": "zhangsan",
    "password": "345dasf",
    "safety_verify_code": "test",
    "remember": true,
    "agree_us": true
}

### 

@access_token={{WolfKillerUserLogin.response.body.access_token}}

# @name WolfKillerUserLogOut

GET {{host}}/user/logout HTTP/1.1
Cookie: auth=0092f7d3a58c877df398283abea48726


###

# @name WolfKillerUserRegister
POST {{host}}/account/register HTTP/1.1
Content-Type: application/json;charset=utf-8

{
    "email": "devtest@test.com",
    "password": "345dasf",
    "secend_password": "345dasf",
    "nick_name": "nibaba",
    "prefix": "86",
    "phone_number": "13888888888",
    "safety_verify_code": "66666",
    "agree_us": true
}
###