@host=http://localhost:3000

# @name WolfKillerHomePage
GET {{host}} HTTP/1.1

###
# @name WolfKillerUserInfo

GET {{host}}/user HTTP/1.1




###
GET  {{host}}/user/login HTTP/1.1



###
# @name WolfKillerUserLogin
POST {{host}}/user/login HTTP/1.1
Content-Type: application/json;

{
    "firstName": "yang",
    "lastName": "add",
    "email": "65656@qq.com",
    "password": "Aa123456",
    "agreeTerms": false,
    "loyalty": true
}


@auth = {{WolfKillerUserLogin.response.headers}}

### 

# @name WolfKillerUserLogOut

GET {{host}}/user/logout HTTP/1.1
Cookie: auth=0092f7d3a58c877df398283abea48726


###
POST {{host}}/user/filter HTTP/1.1

{
    "id":1650
}